version: '3.3'

services:
  mongo:
    image: mongo:3.5.13
    ports:
      - "27017:27017"
    networks:
      - net

  resque:
    build:
      context: .
    image: kinghuang/techcrunchsf2017
    ports:
      - "3000:3000"

networks:
  net:
