version: '3.3'

services:
  mongo:
    image: mongo:3.5.13
    ports:
      - "27017:27017"
    networks:
      - net

  resque:
    image: kinghuang/techcrunchsf2017
    environment:
      - HOST=0.0.0.0
      - MONGO_HOST=mongodb://mongo/resque
    ports:
      - "3000:3000"
    networks:
      - net

networks:
  net:
